### ISSUE TITLE
Scheduler RuntimeError() when compiling large regexp

### ISSUE THREAD

**Issue by noahgibbs** [kddnewton/regular_expression#75]
@chrisseaton - I should probably tag you on this one...

~~~
noah@Noahs-MacBook-Pro-3 regular_expression % irb
irb(main):001:0> require_relative "lib/regular_expression"
=> true
irb(main):002:0> pat = "a?" * 50 + "a" * 50
=> "a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
irb(main):003:0> p = RegularExpression::Pattern.new(pat)
=> #<RegularExpression::Pattern:0x00007fa91010e8a0 @bytecode=#<RegularExpression::Bytecode::Compiled:0x00007fa8d8864f10 @insns=[#<RegularExpression::Bytecode::Insns::PushIndex:0x...
irb(main):004:0> p.compile(compiler: RegularExpression::Compiler::Ruby)
Traceback (most recent call last):
        6: from /opt/rubies/2.7.2/bin/irb:23:in `<main>'
        5: from /opt/rubies/2.7.2/bin/irb:23:in `load'
        4: from /opt/rubies/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        3: from (irb):4
        2: from /Users/noah/src/github.com/kddnewton/regular_expression/lib/regular_expression/pattern.rb:14:in `compile'
        1: from /Users/noah/src/github.com/kddnewton/regular_expression/lib/regular_expression/scheduler.rb:81:in `schedule'
RuntimeError ()
irb(main):005:0>~~~

**Comment by chrisseaton** [comment]
Hmmm I'll make all possible things like this fallback!

**Comment by noahgibbs** [comment]
Cool. This one takes a really long time, and segfaults in fisk when x86-compiled. But it doesn't appear to die in the scheduler any more :-)
